name: WindowsNatives

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./native/WinRestarter/
        
    steps:
    - uses: actions/checkout@v4
############################ WindowsRestarter ############################
# WindowsRestarter X64
    - run: git reset --hard
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build 
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=1
        build-args:  --config Release
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRestarter/build/Release/restarter64.exe
        if-no-files-found: error
# WindowsRestarter X86
    - run: git reset --hard
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=0 TARGET_ARM64=1
        build-args:  --config Release
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRestarter/build/Release/restarter-aarch64.exe
        if-no-files-found: error
# WindowsRestarter ARM64
    - run: git reset --hard
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=0 TARGET_ARM64=0
        build-args:  --config Release
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRestarter/build/Release/restarter.exe
        if-no-files-found: error
############################ WinRunner ############################
# WinRunner X64
    - run: git reset --hard
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=1
        build-args:  --config Release
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRunner/build/Release/runnerw64.exe
        if-no-files-found: error
# WinRunner X86
    - run: git reset --hard
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=0 TARGET_ARM64=1
        build-args:  --config Release
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRunner/build/Release/runnerw-aarch64.exe
        if-no-files-found: error
# WinRunner ARM64
    - run: git reset --hard
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=0 TARGET_ARM64=0
        build-args:  --config Release
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRunner/build/Release/runnerw.exe
        if-no-files-found: error

