name: WindowsNatives

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./native/WinRestarter/
        
    steps:
    - uses: actions/checkout@v2

    - name: Windows Restarter X64
    - uses: nicksnell/action-reset-repo@master
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build 
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=1
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRestarter/Release/restarter64.exe

    - name: Windows Restarter ARM64
    - uses: nicksnell/action-reset-repo@master
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=0 TARGET_ARM64=1
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRestarter/Release/restarter64.exe

    - name: Windows Restarter X86
    - uses: nicksnell/action-reset-repo@master
    - uses: threeal/cmake-action@main
      with:
        generator: Visual Studio 17 2022
        source-dir: ./native/WinRestarter
        build-dir: ./native/WinRestarter/build
        options: CMAKE_BUILD_TYPE=Release TARGET_X64=0 TARGET_ARM64=0
    - uses: actions/upload-artifact@v4
      with:
        path: ./native/WinRestarter/Release/restarter-aarch64.exe
